name: Run BDD Test on PR

on:
  pull_request:
    branches:
      - develop #Trigger only when the PR is made as main branch

jobs:
  run-bdd-tests:
    runs-on: windows-latest

    steps:
    #Checkout the pr code
    - name: Checkout code
      uses: actions/checkout@v2

    #Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' #Install Node.js

    #Install Project dependencies
    - name: Install Dependencies
      run: npm install

    #Run BDD Tests with specified tag 
    - name: Run BDD tests with tags
      run: |
        PR_DESCRIPTION=${curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
        #Extract tags from PR description
         $TAGS = $PR_DESCRIPTION | ConvertFrom-Json | Select-Object -ExpandProperty body | Select-String -Pattern "@\w+" | ForEach-Object { $_.Line.Trim() }
        npm run test:bdd -- --tags $TAGS
    #Send email with test results
    - name: Send email with test results
      if: success()
      run: |
      echo "Sending email with BDD test results"
