name: Run BDD Test on PR

on:
  pull_request:
    branches:
      - main #Trigger only when the PR is made as main branch

jobs:
  run-bdd-tests:
    runs-on: windows-latest

    steps:
    #Checkout the pr code
    - name: Checkout code
      uses: actions/checkout@v2

    #Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' #Install Node.js

    #Install Project dependencies
    - name: Install Dependencies
      run: npm install

    #Extract BDD tags
    - name: Extract BDD tags
      id: extract_tags
      run: |
      echo "Extracting BDD tags from description..."
      TAGS=${echo "${{ github.event.pull_request.body }}"}
      echo "BDD_TAGS=${TAGS}" >> $GITHUB_ENV


    #Run BDD Tests with specified tag 
    - name: Run BDD tests
      if: env.BDD_TAGS != '' 
      run: |
        echo "Running BDD tests for tags: $BDD_TAGS"
        npx cucumber-js --tags "$BDD_TAGS"

    #Send email with test results
    - name: Send email with test results
      if: success()
      run: |
      echo "Sending email with BDD test results"
